[settings]
  buildImage = false

[[container.copy.files]]
sourceFile="./resources.json"
target="/home/ballerina/resources.json"

[[container.copy.files]]
sourceFile="resources2.json"
target="/home/ballerina/resources2.json"
